Add error builder to SVG widget
dnfield/flutter_svg pull request #625
Opened 2021-12-05 16:17 UTC by xal

Related issues: #448, #535 
Similar old PR: https://github.com/dnfield/flutter_svg/pull/277

2021-12-05 20:53 UTC, dnfield requested changes
Please add a test.

2021-12-05 20:53 UTC, dnfield commented on lib/svg.dart
> +    dynamic error,
Please avoid dynamic.

```suggestion
    Object error,
```

2021-12-05 20:53 UTC, dnfield commented on lib/svg.dart
> +  /// The error widgeet to use while fetching, decoding, or parsing fails.
```suggestion
  /// A builder to call if fetching, decoding, or parsing fails.
```

2021-12-20 17:36 UTC, closed without merging

2022-06-01 11:27 UTC, mekhri-codex commented
@xal why it's closed? would it be posted later? I can't find a way to catch exceptions to display errorWidget

2022-06-01 21:27 UTC, xal commented
> @xal why it's closed? would it be posted later? I can't find a way to catch exceptions to display errorWidget

Unfortunately I don't have time and enough experience with ui testing in flutter to write tests for this PR. I use my changes in my app via fork